### ISSUE TITLE
Error: The process '/usr/bin/security' failed with exit code 1

### ISSUE THREAD

**Issue by scriptBoris** [Apple-Actions/import-codesign-certs#68]
![image](https://github.com/Apple-Actions/import-codesign-certs/assets/29772096/bc4b521f-04a9-4f79-bed1-2a02048b60b5)

I used v2 and v3 - any way no result.
And i completed by instructions in readme. 
On my github secrets has: 
APPLE_CERTIFICATE as base64 file .p12 (private key & certificate)
APPLE_CERTIFICATE_PASSPHRASE  as simple text typing by me (just when i created .p12 file, i assigned simple "123" password)

My YML:
```
jobs:
  build:
    runs-on: macos-latest

    env:
      APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
      APPLE_CERTIFICATE_PASSPHRASE: ${{ secrets.APPLE_CERTIFICATE_PASSPHRASE }}
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # mac
    - name: Set XCode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
        
    - name: Install Apple Certificate and Provisioning Profile
      uses: apple-actions/import-codesign-certs@v2
      with: 
        p12-file-base64: $APPLE_CERTIFICATE
        p12-password: $APPLE_CERTIFICATE_PASSPHRASE

    - name: Download Provisioning Profiles
      id: provisioning
      uses: apple-actions/download-provisioning-profiles@v1
      with: 
        bundle-id: com.haykgalstyan.speceqmobile
        profile-type: 'IOS_APP_STORE'
        issuer-id: $APP_STORE_CONNECT_ISSUER_ID
        api-key-id: $APP_STORE_CONNECT_KEY_ID
        api-private-key: $APP_STORE_CONNECT_PRIVATE_KEY
```
